language: node_js
node_js:
- 9.8.0
sudo: false
os:
  #- osx
  #- linux
  - windows

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
install:
- npm install
after_success:
- npm install -g vsce;
- vsce package;
deploy:
- provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: ppparihar/GoTestExplorer
    tags: true
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: ppparihar/GoTestExplorer
    tags: true
    branch: master
